http://localhost:7788

### RFC2616 format

GET /
Host: localhost:7788
Accept: text/html

###

GET /
Host: 172.16.10.68:7788
Accept: text/html

###

GET /api/customers
Host: localhost:7788
Accept: application/json

###

GET /api/customers/4
Host: localhost:7788
Accept: application/json

### add a new customer using post

POST /api/customers
Host: localhost:7788
Accept: application/json
Content-Type: application/json

{
    "name": "Kishore Kumar",
    "city": "Vasco", 
    "email": "kishore.kumar@xmpl.com"
}
### update an existing customer (based on id)

PUT /api/customers/4
Host: localhost:7788
Accept: application/json
Content-Type: application/json

{
  "name": "Umesh Rao",
  "city": "Bangalore",
  "email": "umesh.rao@xmpl.com"
}

### delete an existing customer (based on id)

DELETE /api/customers/4
Host: localhost:7788
Accept: application/json
